### ISSUE TITLE
xin database ngân hàng

### ISSUE THREAD

**Issue by ldtrng** [itialan/QuanLyVatTu_CSDLPT_PTITHCM#3]
bạn ơi, có thể cho mình xin file đề tài CSDL phân tán của thầy Thư được không bạn. Mình đang cần cái database ngân hàng, cảm ơn bạn nhiều

**Comment by haydxxn** [comment]
[DE4-NGAN HANG_PhanTan.docx](https://github.com/itialan/QuanLyVatTu_CSDLPT_PTITHCM/files/6243864/DE4-NGAN.HANG_PhanTan.docx)
[nganhang.txt](https://github.com/itialan/QuanLyVatTu_CSDLPT_PTITHCM/files/6243876/nganhang.txt)

đây bạn nhé!

**Comment by ldtrng** [comment]
Mình cảm ơn nhiều nhé!

Vào Th 5, 1 thg 4, 2021 vào lúc 20:38 Hoa Ngo ***@***.***>
đã viết:
